// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
import * as bootstrap from "bootstrap";

import { application } from "./application"

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import StatusController from "./status_controller"
application.register("status", StatusController)

window.onload = function() {
  window.scrollTo(0, 0);
}

window.bootstrap = bootstrap;
